### ISSUE TITLE
Using SCRuB on a large dataset

### ISSUE THREAD

**Issue by prototaxites** [Shenhav-and-Korem-labs/SCRuB#1]
Hi! This is a really exciting looking piece of software - many thanks for developing it, I'm very interested in giving it a try.

I have a large amplicon sequencing dataset of 1,050 samples not including extraction and PCR blank controls. The samples were extracted in batches of 30, with an extraction negative in each batch. Samples were then amplified over 16 PCR plates in total, with PCR negatives in some but not all plates.

What would be the best way to apply SCRuB to this dataset? Does metadata specifying which extraction a sample belongs to go in the `sample_type` column? Would samples from different plates need to be separated and run independently?

**Comment by gaustin15** [comment]
Hi @prototaxites, thanks for the interest is SCRuB!

Currently, the SCRuB function expects to be given only samples from the same plate, so the samples from different plates need to be separated and fed into SCRuB independently. 

So, for your use case, my recommendation would be the following:
1) First run SCRuB in parallel across each extraction batch of 30
2) Using the output of step (1), run SCRuB in parallel across each of the 16 PCR batches that did include PCR negatives.
3) For the PCR batches without negatives, try running SCRuB using 3 or 4 controls from other batches, but without using the spatial component of the metadata. The controls could either be selected randomly, or based on those with the lowest estimated level of well-to-well leakage, as determined in step (2). 

Please let me know if you run into any issues with this approach. In the future, we might also add in additional features in SCRuB to directly handle use cases such as this one.

**Comment by prototaxites** [comment]
Hi, apologies for the late reply (haven't had time to look at this for a while), but wanted to say thanks for the suggestions! I've got the package working now, just working on writing a batching system 😁

**Comment by gaustin15** [comment]
Awesome, thanks for following up! Please let us know if you have other questions, or if you'd like any support for running SCRuB across batches
