### ISSUE TITLE
order of decontamination

### ISSUE THREAD

**Issue by kristiho** [Shenhav-and-Korem-labs/SCRuB#12]
Hi and thanks for this very interesting tool!

After reading both the paper and tutorials, i am confused about the correct order of decontamination when I have both extraction controls and libraryprep controls.

As stated on the R tutorial: "_Based on the analysis from SCRuB’s manuscript, we recommend to perform decontamination in the order in which contaminants are introduced. In this case, this corresponds to the following control order: control_order <- c("control blank library prep", "control blank DNA extraction")_". This actually sounds to me as opposite of the order which contaminants are introduced??

In the [Qiime tutorial ](https://shenhav-and-korem-labs.github.io/SCRuB/QIIME2-Tutorial.html)(python interface) it says order should be "_control blank DNA extraction", "control blank library prep_", while opposite stated in cli interface.

In the Methods section of the paper it is stated that for the plasma samples (Poore et al) the order was "_first 16 extraction controls, then 14 library prep controls_". The same order I also find in the R code ([Run_plasma_deconts_and_preds.R](Plasma/Run_plasma_deconts_and_preds.R))

Contrary, for the Tumor samples (Nejman et al) decontamination order is stated in Methods as: "_PCR-NTC, DNA extraction controls, parafin controls_". (and finally yet another order in the R script [decontaminate_cancers.R](Tumor/decontaminate_cancers.R): "_Parafin, NTC, extraction_".

Did i misunderstand something here? what is the reason for this discrepancy? and most importantly, what is the correct order to use :)

best,
Kristian

**Comment by gaustin15** [comment]
In general, our recommendation is to follow the analyses described in the paper, so if you have specifically library prep and extraction controls, our recommended order is, as you touched on, `extraction` then `library prep` (we’ll adjust the typo in the documentation page to remove any confusion in the future). 

For the Nejman analysis, which includes ntc/extraction/paraffin, there are additional subtleties, since paraffin samples were only available for a subset of centers (and the ordering of the paraffins isn’t as relevant since they weren’t available for the melanoma samples and thus didn’t impact the analysis), so the important distinction here is the order between ntc and extraction, for which the code and paper are consistent. Ultimately, our recommendations for those who do have paraffin controls would also follow the order described in the paper, which is ntc-extraction-paraffin.

**Comment by gaustin15** [comment]
Another point to add is that there are a lot of factors that might affect what the optimal order of decontamination is (such as the levels of contamination, number of samples/controls, noise, etc....), and while our analyses followed certain strategies, how to determine the best order for most scenarios remains an area we’re still investigating. Ultimately, the results from our paper don’t justify one strategy for ordering controls over the other, and the only comment we wrote on this is that researchers should consider the order in which they run SCRuB. 
While the recommendation we provide in our documentation, which is to follow the order in which the contaminants are introduced, is a reasonable and generalizable strategy  that worked in our hands, there might be factors specific to your study that might make it better to use some other order.

**Comment by kristiho** [comment]
Thank you for your answer! i understand there might be other factors influencing the best order. i would intuitively prefer "libraryprep(ntc) then extraction" (as you suggest in the paper and fig 4a), but this would indicate opposite order than contaminants were introduced, Still, in your first post here you repeat the general recommendation remains "extraction then libraryprep"...?

**Comment by gaustin15** [comment]
If your intuitive preference is for this order, then as far as we’re concerned that’s a reasonable application of SCRuB. As mentioned above, the order used for this specific analysis in our paper was based on an empirical evaluation. While we do have some opinions for why we frame the ‘generally recommended’ order as we do, we find that there are good arguments for both orders.

**Comment by gaustin15** [comment]
Control order in documentation pages adjusted [here](https://github.com/Shenhav-and-Korem-labs/SCRuB/commit/eec5d4271b033e953e94d76409c70c1b60d90776)
